name: CI - Push to Main

on:
  workflow_dispatch:
    inputs:
      importAll:
        default: false
        required: false
        type: boolean
        description: Enable, if you want to import all TODOs. Runs on checked out branch! Only use if you're sure what you are doing. (requires run_todo_bot to be true)
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  issues: write
  repository-projects: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  mergebot:
    name: Merge Bot
    if: ${{ github.repository_owner == 'withstudiocms' && github.event_name != 'workflow_dispatch' && github.event.commits[0].message != '[ci] lint' }}
    uses: withstudiocms/automations/.github/workflows/mergebot.yml@main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MERGEBOT }}

  lunaria-build:
    name: Build Lunaria Overview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}
    
      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - name: Build Lunaria Overview
        run: pnpm ci:lunaria:build

      - name: Upload Overview
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/lunaria/"

  lunaria-deploy:
    name: Deploy Lunaria Overview
    runs-on: ubuntu-latest
    needs: lunaria-build
    environment:
      name: github-pages
      url: ${{ steps.lunaria-build.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4